### ISSUE TITLE
新規投稿 & 詳細ページ機能と画面の作成をお願いします。

### ISSUE THREAD

**Issue by good1luck21** [good1luck21/blog_app#1]
## 新規予定作成ファイル
- [ ] app/views/posts/new.html.erb
- [ ] app/views/posts/show.html.erb

## 編集予定ファイル
- [ ] app/controllers/posts_controller.rb
- [ ] config/routes.rb

## 準備済みファイル
- Postテーブル用のmigrationファイルは作成済みです。
  - https://github.com/good1luck21/blog_app/blob/master/db/migrate/20210102042430_create_posts.rb 
- テストデータ用のサンプルデータファイル作成済みです。
  - https://github.com/good1luck21/blog_app/blob/master/db/seeds.rb

上記を利用してデータベースとサンプルの登録をお願いします。

## 環境情報
- ruby version 2.5.1
- rails version 5.1.7

上記環境は任意の環境に変更をお願いします。

## TODO:
- [ ] データ登録し、一覧表示を確認する
- [ ] 上記新規予定作成ファイルを作成し、チェックを入れる。
- [ ] 編集予定ファイルにも同様に編集し、チェックを入れる。
- [ ] 新規投稿と詳細ページ表示が出来ることを確認する。
